### ISSUE TITLE
The model gives errors without the --sql flag

### ISSUE THREAD

**Issue by aman229** [Leftice/AirConcierge#1]
Some of the variable like total_gp_correct are only computed in the args.sql blocks, but they give error if I run the model without sql part

CUDA_VISIBLE_DEVICES=0 python air.py --air --save_dir 'runs/AirConciergeSQL-epoch5/' --model_dir 'checkpoints/AirConciergeSQL-epoch5/' --checkpoint_every 2000 --adam --action_att --clip 1.0 --batch_size 32 --max_len 320 --mask --sigmkb --shuffle

**Comment by Leftice** [comment]
Thank you very much for your question. I'm sorry because I didn't add the code of the AirDialogue paper implementation during the integration, which caused problems when there is no "--sql", but in fact, without "--sql", it is actually the method used in AirDialogue paper (without using the objective for training the SQL par), you may refer to the coded link implementation of the AirDialogue paper and modify it to meet your needs, I'm sorry I didn't put the part of the implementation in my codebase. I hope this answer can help you. Thank you for taking the time to watch.
